[package]
name = "hc_seed_bundle_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hc_seed_bundle_cli"
path = "src/main.rs"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.4", features = ["derive"] }
color-eyre = "0.6"
dialoguer = "0.11.0"
hc_seed_bundle = { version = "0.6.2" }
hex = "0.4.3"
holochain_types = "0.5.3"
thiserror = "2.0.12"
tokio = { version = "1.0", features = ["full"] }
